[package]
name = "cloudflare-bypasser"
version = "0.1.2"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
repository = "https://github.com/AurevoirXavier/cloudflare-bypasser"
description = "A crate to bypass Cloudflare's anti-bot page, inspired by python module [cloudflare-scrape](https://github.com/Anorov/cloudflare-scrape)"
readme = "README.md"
keywords = ["bypass", "cloudflare"]
license = "MIT/Apache-2.0"

[dependencies]
fake-useragent = "0.1.2"
regex = "1.1.0"
reqwest = "0.9.9"
url = "1.7.2"
